Repository shwlee/player, pull requests merged in 2024-11, with the labels that each got.

#6 turn 인자 추가 + GameMessage 객체를 구조분해할당 가능하도록 수정.
  Runners/Python/PyHost/models/game_message.py
  Runners/Python/PyHost/services/game_service.py
Labels: code review

#7 응답 형식을 수정합니다.
  Runners/Python/PyHost/routes/game.py
  Runners/Python/PyHost/routes/player.py
Labels: enhancement, code review

#8 game logger 추가
  Runners/Python/PyHost/main.py
  Runners/Python/PyHost/services/game_logger.py
  Runners/Python/PyHost/services/game_service.py
Labels: code review

#10 로그 파일 경로 생성 구문 변경.
  Runners/Javascript/JsHost/routes/gameRoute.js
  Runners/Javascript/JsHost/services/gameService.js
Labels: code review

#12 PyHost cleanup 이후 로그 파일 잠기는 증상 수정.
  Runners/Python/PyHost/services/game_logger.py
  Runners/Python/PyHost/services/game_service.py
Labels: enhancement
